<a href="https://colab.research.google.com/github/ReefAmarin/HTU-DS-2021/blob/main/Faisal_Computation_on_Arrays_Broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 ***The term broadcasting refers to how numpy treats arrays with different Dimension during arithmetic operations which lead to certain constraints, the smaller array is broadcast across the larger array so that they have compatible shapes***

In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3])
b = np.array([2, 2, 2]) 
a * b

array([2, 4, 6])

In [ ]:
a1 = np.array([1,2 ,3])
b1 = np.array([4,5,6])

a1 + b1

array([5, 7, 9])

 **Illustrate the Broadcasting**

In [ ]:
np.arange(3) + 5

array([5, 6, 7])

In [ ]:
np.ones((3,3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [ ]:
np.arange(3).reshape(3,1) + np.arange(3)

![Broadcasting Visual](https://github.com/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/figures/02.05-broadcasting.png?raw=1)

**Rules:**

1.   Having the same number of shape
2.   Having the same number of rows or columns AND the other rows or columns equal to one
3.   Number one can match with any number





**Reshape & Newaxis**

**np.reshape:
It is used to reshape the array to the desired layout**


**np.newaxis:
It is used to increase the dimension of the existing array**

In [9]:
y = np.arange(8)
y.shape

(8,)

In [10]:
y = y.reshape(4,2)
y.shape

(4, 2)

In [11]:
z = np.arange(6)
z.shape

(6,)

In [12]:
z.shape

(6,)

In [13]:
z = z[:,np.newaxis]
z.shape

(6, 1)

In [14]:
z

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

![Broadcasting Visual](https://i.stack.imgur.com/zkMBy.png)

**Example 1**

In [15]:
x = np.arange(6).reshape(2,3)

y1 = np.arange(6).reshape(2,3) # compatible
y2 = np.arange(8).reshape(2,4) # compatible
y3 = np.arange(3).reshape(1,3) # compatible
y4 = np.arange(3) # compatible


y5 = np.arange(6).reshape(3,2) # NOT compatible
y6 = np.arange(2) # NOT compatible
y7 = np.arange(3).reshape(3,1) # NOT compatible

In [19]:
x + y2

ValueError: ignored

**This rule is exclusive for ND Arrays for broadcasting check the  match dimensions number from right to left (Number one can match with any number)**

**Example 2 & 3 ilustrate the rule**

**Example 2 (3D,2D) Arrays**

In [ ]:
y = np.arange(60).reshape(4,3,5)

x1 = np.arange(60).reshape(4,3,5) # compatible
x2 = np.arange(4).reshape(4,1,1) # compatible
x3 = np.arange(20).reshape(4,1,5) # compatible
x4 = np.arange(5).reshape(1,1,5) # compatible
x5 = np.arange(12).reshape(4,3)[:,:,np.newaxis] # compatible
x6 = np.arange(15).reshape(3,5) # compatible
x7 = np.arange(5)

x8 = np.arange(12).reshape(4,3) # NOT compatible
x9 = np.arange(60).reshape(5,4,3) # NOT compatible
x10 = np.arange(4).reshape(1,4,1) # NOT compatible




In [ ]:
y+x1

**Example 3 (More Than 3D)**

In [ ]:
Z = np.arange(120).reshape(5,3,4,2)
R = np.arange(24).reshape(3,4,2)
Z + R

In [ ]:
V = np.arange(48).reshape(2,4,3,2)
N = np.arange(6).reshape(3,2)
V + N

In [ ]:
U = np.arange(90).reshape(3,2,5,3)
Q = np.arange(30).reshape(2,5,3)
U + Q

In [ ]:
L = np.arange(720).reshape(6,5,4,3,2)

M1 = np.arange(2) # compatible
M2 = np.arange(6).reshape(3,2) # compatible
M3 = np.arange(24).reshape(4,3,2,) # compatible
M4 = np.arange(120).reshape(5,4,3,2) # compatible
M5 = np.arange(720).reshape(6,5,4,3,2)# compatible

M6 = np.arange(6) # NOT compatible
M7 = np.arange(30).reshape(6,5) # NOT compatible
M8 = np.arange(120).reshape(6,5,4) # NOT compatible

In [ ]:
L + M1

In [ ]:
# G = np.random.random(5,3,6,9,7,4,1,2,5)
# K = np.random.random()


 **Centering an Array :**
In mathematics the centering array is the subtracting the mean of the components of the vector from every component of that vector.

In [ ]:
X = np.random.random((10,3))
X

Compute the mean of each feature using the ``mean`` aggregate across the first dimension:

In [ ]:
Xmean = X.mean(0)
Xmean

And now we can center the ``X`` array by subtracting the mean (this is a broadcasting operation):

In [ ]:
X_centered = X - Xmean
X_centered

To double-check that we've done this correctly, we can check that the centered array has near zero mean:

In [ ]:
X_centered.mean(0)

### Plotting a two-dimensional function

One place that broadcasting is very useful is in displaying images based on two-dimensional functions.
If we want to define a function $z = f(x, y)$, broadcasting can be used to compute the function across the grid:

In [ ]:
# x and y have 50 steps from 0 to 5
x = np.linspace(0, 5, 50)
y = np.linspace(0, 5, 50)[:, np.newaxis]

z = np.sin(x) ** 10 + np.cos(10 + y * x) * np.cos(x)

In [ ]:
x

In [ ]:
y

In [ ]:
z

We'll use Matplotlib to plot this two-dimensional array (these tools will be discussed in full in [Density and Contour Plots](04.04-Density-and-Contour-Plots.ipynb)):

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt

In [ ]:
plt.imshow(z, origin='lower', extent=[0, 5, 0, 5],
           cmap='viridis')
plt.colorbar();

The result is a compelling visualization of the two-dimensional function.

<!--NAVIGATION-->
< [Aggregations: Min, Max, and Everything In Between](02.04-Computation-on-arrays-aggregates.ipynb) | [Contents](Index.ipynb) | [Comparisons, Masks, and Boolean Logic](02.06-Boolean-Arrays-and-Masks.ipynb) >

<a href="https://colab.research.google.com/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/02.05-Computation-on-arrays-broadcasting.ipynb"><img align="left" src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open in Colab" title="Open and Execute in Google Colaboratory"></a>
