<a href="https://colab.research.google.com/github/ReefAmarin/HTU-DS-2021/blob/main/Numpy_exercises-reef.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises


#### 1. Import the numpy package under the name `np` (★☆☆) `hint: import … as`

In [2]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆) `hint: vector is a single raw array`

In [2]:
import numpy as np
arr=np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 3. How to find the memory size of any array, creat a random 5x6 array and check the sizs (★☆☆)

In [1]:
import numpy as np
arr2=np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10],[1, 2, 3, 4, 5], [6, 7, 8, 9, 10],[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print("Print array:")  
print(arr2) 
print("\n")
print("Memory Size: ")  
print(arr2.itemsize)

SyntaxError: ignored

#### 4. How to get the documentation of the numpy add function from the command line? (★☆☆) `hint: use info or ?`

#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆) `hint: array[x]`

In [10]:
import numpy as np
arr3=np.zeros(10)
arr3[4]=1
print(arr3)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector (single raw array) with values ranging from 10 to 49 (★☆☆) `hint: arange`

In [4]:
import numpy as np
arr4=np.arange(10, 50,1)
print(arr4)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Show how you can Reverse a vector (first element becomes last) (★☆☆)`hint: use index of -1`

In [1]:
import numpy as np
arr5=np.arange(49,9,-1)
print(arr5)


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) `hint: use range and reshape!`

In [41]:
import numpy as np
arr6=np.arange(0,9)
arr6.reshape(3,3)
print(arr6)

[0 1 2 3 4 5 6 7 8]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆) `hint: use the np.nonzero`

In [7]:
import numpy as np
arr7=np.array([1,2,0,0,4,0])
print(np.nonzero(arr7))

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) `hint: use index and use np.eye`
the following is an example of 5x4 identity matrix


```
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

```



In [11]:
import numpy as np
np.eye(3, k=3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) `hint: np.random.random`

In [13]:
from numpy import random

x = random.randint(100, size=(3,3,3))

print(x)

[[[ 9 15 86]
  [69 23 64]
  [82 24  7]]

 [[72 70 77]
  [22 83 39]
  [22 43 35]]

 [[ 2 27  7]
  [ 7 12 57]
  [81 74 65]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) `hint: min, max`

In [14]:
from numpy import random

x = random.randint(100, size=(10,10))

print(x) 

[[20 67 97 56 99 75 38 93 71 32]
 [16 33 20 27 24 49 82 49 70 55]
 [ 3 55 65 54  7 30 42 88  9  5]
 [46 42  4 89 38  9 51 10  9 64]
 [61 97  9 58 27 46  3 75  5  1]
 [99  8 24  8 65 95 22 70 95 62]
 [56  2 46 45 43 42 26 13 24 32]
 [ 2 37 17 43 11 31 47 37 16 99]
 [14 11 89 37 54 15 82 32 56 12]
 [64 41 96 11 36 63 59 55 16 91]]


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) `hint: mean`

In [18]:
from numpy import random

x = random.randint(100, size=(30))
print(np.mean(x))
print(x)

53.96666666666667
[53 23 86 83 87 88 85 88 37 67 32 48 11  7 43 19 82 75 81 20 43 31 32 41
 76 85 37 34 69 56]


#### 15. Create a 2d array as following, with 1 on the border and 0 inside.

*   List item
*   List item

. see generated array (★☆☆)



```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
```



In [19]:

import numpy as np
arr9 = np.ones((10,10))
arr9[1:-1,1:-1] = 0
print(arr9)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★★☆) `hint: see generated array np.pad   `

In [26]:

import numpy as np
arr10 = np.zeros((10,10))
arr10[1:-1,1:-1] = 1
print(arr10)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[ 1. nan  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```


answer :False

 ####18  What is the result of the following expression? (★☆☆) `hint: indexing the nan using np.nan`



```
Z = np.ones((5,5))
Z[0,1]=np.nan
Z
```



In [ ]:
[[ 1. nan  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]

#### 18. Now, use this expression to find the index of your nan


```
np.argwhere(x!=x)    Hint: x is your array
```




In [27]:
from numpy import random

x = random.randint(100, size=(3,3,3))
print(np.argwhere(x!=x))

[]


20. Generate the following array 


```
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])
```



In [40]:
import numpy as np
arr5=np.arange(0,16,1)
narr=arr5.reshape(4,4)
print(narr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 19. Extract the following values `array([ 1,  6, 11, 16])`. ` Hint: use np.diagonal()`

In [66]:
import numpy as np
a1=np.array([1, 6, 11,16])
np.fliplr(a1).diagonal()

ValueError: ignored

In [ ]:
Z

array([7.29e-44, 1.96e-44, 2.80e-45, 1.35e-43, 5.75e-44, 9.95e-44,
       9.25e-44, 7.85e-44, 6.31e-44, 5.61e-45], dtype=float32)

#### 20. Try to use `np.diag` to Create a 5x5 matrix with diagonal values 11,11,11,11 (★★☆) Hint: use np.diag with k=0 and [11,11,11,11]. -- diag([11,11,11,11],k=-0)

In [44]:
import numpy as np
x = np.diag([11, 11, 11, 11, 11])
print(x)

[[11  0  0  0  0]
 [ 0 11  0  0  0]
 [ 0  0 11  0  0]
 [ 0  0  0 11  0]
 [ 0  0  0  0 11]]


#### 21.  Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) `Hint: use k=-1 when calling np.diag`

In [45]:
import numpy as np
x = np.diag([1, 2, 3, 4])
print(x)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]




```
`# This is formatted as code`
```

####22. Create a 8x8 matrix and fill it with a given pattern (★☆☆) Hint: use np.zeros and do the replace 



```
[['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']]
```



In [57]:
import numpy as np
x = np.zeros((8,8),dtype=str)
x[1::2,::2] = 'M'
x[::2,1::2] ='O'
print(x)

[['' 'M' '' 'M' '' 'M' '' 'M']
 ['O' '' 'O' '' 'O' '' 'O' '']
 ['' 'M' '' 'M' '' 'M' '' 'M']
 ['O' '' 'O' '' 'O' '' 'O' '']
 ['' 'M' '' 'M' '' 'M' '' 'M']
 ['O' '' 'O' '' 'O' '' 'O' '']
 ['' 'M' '' 'M' '' 'M' '' 'M']
 ['O' '' 'O' '' 'O' '' 'O' '']]


In [58]:
import numpy as np
x = np.zeros((8,8),dtype=str)
x[1::2,::2] = 'o'
x[::2,1::2] ='M'
print(x)

[['' 'M' '' 'M' '' 'M' '' 'M']
 ['o' '' 'o' '' 'o' '' 'o' '']
 ['' 'M' '' 'M' '' 'M' '' 'M']
 ['o' '' 'o' '' 'o' '' 'o' '']
 ['' 'M' '' 'M' '' 'M' '' 'M']
 ['o' '' 'o' '' 'o' '' 'o' '']
 ['' 'M' '' 'M' '' 'M' '' 'M']
 ['o' '' 'o' '' 'o' '' 'o' '']]


[link text](https://)#### 23. Use the `np.tile` to generate the same pattern 

```
[['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']]
```



[['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']
 ['' 'O' '' 'O' '' 'O' '' 'O']
 ['M' '' 'M' '' 'M' '' 'M' '']]


#### 24. Generate then Normalize a 5x5 random matrix (★☆☆)  `hint: Normalization_array = (x_arr -mean_value(x))/std_value(x)`

In [59]:
import numpy as np
x= np.random.random((5,5))
print(x)

[[0.72211063 0.07887341 0.03839417 0.98326647 0.00619623]
 [0.85175169 0.44607152 0.3147025  0.35633001 0.47975441]
 [0.64922123 0.88880128 0.97594187 0.56129858 0.7458592 ]
 [0.33272001 0.80056125 0.23181131 0.90304221 0.97933315]
 [0.31298926 0.45125532 0.38228638 0.719181   0.71393152]]


#### 25. generate any 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

where 

```
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
```
will return

```
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]
```




In [64]:
Z = np.arange(11)
m = np.where(Z[3:8])
Z[m] *= -1
print(Z)

[ 0 -1 -2 -3 -4  5  6  7  8  9 10]


#### 26. Consider an integer vector Z, comment any iligal expressions (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [51]:
Z**Z
#2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
#Z<Z>Z


array([[ 1., nan,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

#### 27. Generate two randon 1D array, How to find common values between two arrays? (★☆☆) `Hint: use intersect1d(Arr1,Arr2)`

In [37]:
import numpy as np 
    
arr1 = np.array([[1, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
arr2 = np.array([[1, 5, 2, 3,3],[5, 6, 7, 2, 3]])
result = np.intersect1d(arr1, arr2)
    
print (result)


[1 2 3 5 6 7]


#### 28. How to ignore all numpy warnings (not recommended)? (★☆☆)

####29. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
False