<a href="https://colab.research.google.com/github/ReefAmarin/HTU-DS-2021/blob/main/Session3_Reef_Amarin_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder 
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [7]:
df_1= pd.read_csv('s3.csv')
df_1.head()

Gender   Age   Salary Purchased
0    Male  19.0  19000.0        NO
1  Female  35.0  20000.0        NO
2  Female  26.0  43000.0        NO
3  Female   NaN  57000.0        NO
4    Male  19.0  76000.0        NO

In [12]:
x_factor =df_1.iloc[:,:-1].values
x_factor
x_factor.shape

(400, 3)

In [13]:
y_factor=df_1.iloc[:,-1].values

In [10]:
imputerObj= SimpleImputer(missing_values =np.nan, strategy='median')

In [11]:
imputerObj.fit(x_factor[:,1:3])
x_factor[:,1:3]=imputerObj.fit_transform(x_factor[:,1:3])
x_factor

array([['Male', 19.0, 19000.0],
       ['Female', 35.0, 20000.0],
       ['Female', 26.0, 43000.0],
       ...,
       ['Female', 50.0, 20000.0],
       ['Male', 36.0, 70000.0],
       ['Female', 49.0, 36000.0]], dtype=object)

In [ ]:

x_factor = df_1.iloc[:, :-1].values
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(drop = 'first'), [0])], remainder='passthrough')
x_factor=np.array(ct.fit_transform(x_factor))
x_factor


array([[1.0, 19.0, 19000.0],
       [0.0, 35.0, 20000.0],
       [0.0, 26.0, 43000.0],
       ...,
       [0.0, 50.0, 20000.0],
       [1.0, 36.0, nan],
       [0.0, 49.0, 36000.0]], dtype=object)

In [ ]:

le = LabelEncoder()
y_factor = le.fit_transform(y_factor)
y_factor

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [ ]:
train_test_split(x_factor,y_factor,test_size=0.2)

[array([[1.0, 40.0, 107000.0],
        [1.0, 23.0, 82000.0],
        [1.0, 34.0, 43000.0],
        [0.0, 36.0, 63000.0],
        [0.0, 48.0, 96000.0],
        [1.0, 20.0, 49000.0],
        [0.0, 28.0, 79000.0],
        [1.0, 39.0, 75000.0],
        [1.0, 29.0, 80000.0],
        [1.0, 60.0, 102000.0],
        [1.0, 18.0, 82000.0],
        [0.0, 53.0, 34000.0],
        [1.0, 19.0, 19000.0],
        [0.0, 39.0, 71000.0],
        [1.0, 49.0, 86000.0],
        [0.0, nan, 42000.0],
        [1.0, nan, 22000.0],
        [1.0, 48.0, 41000.0],
        [0.0, 54.0, 26000.0],
        [1.0, nan, 71000.0],
        [1.0, 59.0, 42000.0],
        [0.0, 22.0, 27000.0],
        [1.0, 35.0, 53000.0],
        [0.0, 23.0, 20000.0],
        [0.0, 38.0, 61000.0],
        [0.0, 27.0, 31000.0],
        [0.0, 39.0, 77000.0],
        [0.0, 46.0, 32000.0],
        [0.0, 33.0, 41000.0],
        [0.0, 35.0, 75000.0],
        [1.0, 56.0, 104000.0],
        [1.0, 28.0, 85000.0],
        [1.0, 41.0, 72000.0],
        [0

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(x_factor, y_factor, test_size = 0.2)
X_train, X_test, y_train, y_test

(array([[0.0, 43.0, 133000.0],
        [0.0, 33.0, 31000.0],
        [0.0, 59.0, 88000.0],
        [1.0, 34.0, 43000.0],
        [0.0, 42.0, 73000.0],
        [1.0, 24.0, 84000.0],
        [1.0, nan, 71000.0],
        [0.0, 49.0, 36000.0],
        [0.0, 41.0, 87000.0],
        [0.0, 19.0, 70000.0],
        [1.0, 25.0, 90000.0],
        [1.0, 49.0, 39000.0],
        [0.0, 26.0, 80000.0],
        [0.0, 41.0, 52000.0],
        [0.0, 36.0, 63000.0],
        [0.0, 28.0, 37000.0],
        [0.0, 36.0, 75000.0],
        [0.0, 47.0, 20000.0],
        [1.0, 39.0, 79000.0],
        [1.0, 31.0, 76000.0],
        [0.0, 25.0, nan],
        [1.0, 49.0, 88000.0],
        [0.0, 38.0, nan],
        [0.0, 31.0, 74000.0],
        [0.0, 47.0, 30000.0],
        [1.0, 27.0, 20000.0],
        [1.0, 24.0, 55000.0],
        [1.0, 35.0, 97000.0],
        [0.0, 27.0, 84000.0],
        [0.0, 33.0, 41000.0],
        [1.0, 40.0, 71000.0],
        [0.0, 36.0, 52000.0],
        [0.0, nan, 44000.0],
        [0.0, 46.0,

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,2:] = sc.fit_transform(X_train[:,2:])

X_train

array([[0.0, 43.0, 1.860435545236731],
       [0.0, 33.0, -1.1161116767035297],
       [0.0, 59.0, 0.5472529473219101],
       [1.0, 34.0, -0.7659296505929108],
       [0.0, 42.0, 0.10952541468363645],
       [1.0, 24.0, 0.4305256052850371],
       [1.0, nan, 0.05116174366519997],
       [0.0, 49.0, -0.9702024991574385],
       [0.0, 41.0, 0.5180711118126918],
       [0.0, 19.0, 0.021979908155981727],
       [1.0, 25.0, 0.6056166183403465],
       [1.0, 49.0, -0.8826569926297838],
       [0.0, 26.0, 0.3137982632481641],
       [0.0, 41.0, -0.5032931310099467],
       [0.0, 36.0, -0.18229294040854596],
       [0.0, 28.0, -0.9410206636482202],
       [0.0, 36.0, 0.16788908570207295],
       [0.0, 47.0, -1.4371118673049306],
       [1.0, 39.0, 0.2846164277389459],
       [1.0, 31.0, 0.1970709212112912],
       [0.0, 25.0, nan],
       [1.0, 49.0, 0.5472529473219101],
       [0.0, 38.0, nan],
       [0.0, 31.0, 0.1387072501928547],
       [0.0, 47.0, -1.145293512212748],
       [1.0, 27.0,

In [ ]:
X_test[:,2:] = sc.fit_transform(X_test[:,2:])
X_test

array([[1.0, 19.0, -1.6011310712580247],
       [1.0, 39.0, 0.011948739337746483],
       [1.0, 22.0, -0.28676974410591494],
       [0.0, 29.0, 2.2523373651652068],
       [0.0, 25.0, -1.182925194436899],
       [1.0, 60.0, -1.1530533460925327],
       [1.0, nan, -1.5115155262249265],
       [0.0, 52.0, 1.9536188817215447],
       [1.0, 42.0, -0.07766680569535192],
       [1.0, 36.0, 1.3561819148342225],
       [0.0, 27.0, -1.660874767946757],
       [0.0, 33.0, -0.6452319242383084],
       [1.0, 59.0, 0.10156428437084487],
       [0.0, 53.0, 0.9379760380130967],
       [0.0, 32.0, -1.6310029196023907],
       [0.0, 32.0, -1.6310029196023907],
       [0.0, 31.0, 0.48989831284760466],
       [1.0, 26.0, -0.6153600758939424],
       [1.0, 35.0, -0.017923109006619645],
       [0.0, 42.0, -0.5556163792052101],
       [0.0, 44.0, -1.0036941043707022],
       [1.0, 33.0, -0.10753865403971806],
       [0.0, 51.0, 1.8341314883440805],
       [0.0, 49.0, -1.3322844361587296],
       [0.0, 33.0,